import type { Metadata } from "next";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className=" bg-neutral-800 *:text-white flex justify-center items-center ">
        <div className="w-1/2">{children}</div>
      </body>
    </html>
  );
}
